# Generated by Django 3.1.7 on 2021-03-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("times", models.DateTimeField(max_length=32)),
                ("title", models.CharField(max_length=20)),
                ("pic", models.CharField(max_length=100)),
                ("introduce", models.CharField(max_length=500)),
                ("end", models.NullBooleanField()),
            ],
            options={
                "db_table": "t_notice",
            },
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=20)),
                ("titlt2", models.CharField(max_length=20)),
                ("favorite", models.NullBooleanField()),
                ("img_list", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "t_order_detail",
            },
        ),
    ]
