# Generated by Django 3.1.7 on 2021-03-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carousel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("src", models.CharField(max_length=100)),
                ("background", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "t_carousel",
            },
        ),
    ]
