# Generated by Django 3.1.7 on 2021-03-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_carousel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Share",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("icon", models.CharField(max_length=100)),
                ("text", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "t_share",
            },
        ),
    ]
