# Generated by Django 3.1.7 on 2021-03-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_share"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("sales", models.IntegerField()),
                ("image", models.CharField(max_length=100)),
                ("image2", models.CharField(max_length=100)),
                ("image3", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "t_product",
            },
        ),
    ]
