//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventCloud {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventCloud.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 item_key is not null  的本地化字符串。
        /// </summary>
        internal static string audit_in_role_item_key {
            get {
                return ResourceManager.GetString("audit_in_role_item_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 item_key length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string audit_in_role_item_key_range {
            get {
                return ResourceManager.GetString("audit_in_role_item_key_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 account is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_account {
            get {
                return ResourceManager.GetString("buyer_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 account length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_account_range {
            get {
                return ResourceManager.GetString("buyer_account_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 address is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_address {
            get {
                return ResourceManager.GetString("buyer_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 address is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_address_address {
            get {
                return ResourceManager.GetString("buyer_address_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 address length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_address_address_range {
            get {
                return ResourceManager.GetString("buyer_address_address_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 city is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_address_city {
            get {
                return ResourceManager.GetString("buyer_address_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 city length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_address_city_range {
            get {
                return ResourceManager.GetString("buyer_address_city_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 contact_name is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_address_contact_name {
            get {
                return ResourceManager.GetString("buyer_address_contact_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 contact_name length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_address_contact_name_range {
            get {
                return ResourceManager.GetString("buyer_address_contact_name_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 country is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_address_country {
            get {
                return ResourceManager.GetString("buyer_address_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 country length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_address_country_range {
            get {
                return ResourceManager.GetString("buyer_address_country_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 memo is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_address_memo {
            get {
                return ResourceManager.GetString("buyer_address_memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 memo length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_address_memo_range {
            get {
                return ResourceManager.GetString("buyer_address_memo_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 phone is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_address_phone {
            get {
                return ResourceManager.GetString("buyer_address_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 phone length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_address_phone_range {
            get {
                return ResourceManager.GetString("buyer_address_phone_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 post_code is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_address_post_code {
            get {
                return ResourceManager.GetString("buyer_address_post_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 post_code length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_address_post_code_range {
            get {
                return ResourceManager.GetString("buyer_address_post_code_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 province is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_address_province {
            get {
                return ResourceManager.GetString("buyer_address_province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 province length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_address_province_range {
            get {
                return ResourceManager.GetString("buyer_address_province_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 address length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_address_range {
            get {
                return ResourceManager.GetString("buyer_address_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 auth_app_id is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_auth_app_id {
            get {
                return ResourceManager.GetString("buyer_auth_app_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 auth_app_id length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_auth_app_id_range {
            get {
                return ResourceManager.GetString("buyer_auth_app_id_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 city is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_city {
            get {
                return ResourceManager.GetString("buyer_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 city length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_city_range {
            get {
                return ResourceManager.GetString("buyer_city_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 country is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_country {
            get {
                return ResourceManager.GetString("buyer_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 country length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_country_range {
            get {
                return ResourceManager.GetString("buyer_country_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 email is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_email {
            get {
                return ResourceManager.GetString("buyer_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 email length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_email_range {
            get {
                return ResourceManager.GetString("buyer_email_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 headimgurl is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_headimgurl {
            get {
                return ResourceManager.GetString("buyer_headimgurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 headimgurl length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_headimgurl_range {
            get {
                return ResourceManager.GetString("buyer_headimgurl_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 im_qq is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_im_qq {
            get {
                return ResourceManager.GetString("buyer_im_qq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 im_qq length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_im_qq_range {
            get {
                return ResourceManager.GetString("buyer_im_qq_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 language is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_language {
            get {
                return ResourceManager.GetString("buyer_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 language length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_language_range {
            get {
                return ResourceManager.GetString("buyer_language_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 name is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_name {
            get {
                return ResourceManager.GetString("buyer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 name length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_name_range {
            get {
                return ResourceManager.GetString("buyer_name_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 open_id is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_open_id {
            get {
                return ResourceManager.GetString("buyer_open_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 open_id length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_open_id_range {
            get {
                return ResourceManager.GetString("buyer_open_id_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 phone is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_phone {
            get {
                return ResourceManager.GetString("buyer_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 phone length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_phone_range {
            get {
                return ResourceManager.GetString("buyer_phone_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 postcode is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_postcode {
            get {
                return ResourceManager.GetString("buyer_postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 postcode length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_postcode_range {
            get {
                return ResourceManager.GetString("buyer_postcode_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 province is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_province {
            get {
                return ResourceManager.GetString("buyer_province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 province length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_province_range {
            get {
                return ResourceManager.GetString("buyer_province_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pwd is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_pwd {
            get {
                return ResourceManager.GetString("buyer_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pwd length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_pwd_range {
            get {
                return ResourceManager.GetString("buyer_pwd_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 realname is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_realname {
            get {
                return ResourceManager.GetString("buyer_realname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 realname length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_realname_range {
            get {
                return ResourceManager.GetString("buyer_realname_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 refresh_token is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_refresh_token {
            get {
                return ResourceManager.GetString("buyer_refresh_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 refresh_token length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_refresh_token_range {
            get {
                return ResourceManager.GetString("buyer_refresh_token_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 remark is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_remark {
            get {
                return ResourceManager.GetString("buyer_remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 remark length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_remark_range {
            get {
                return ResourceManager.GetString("buyer_remark_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sex is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_sex {
            get {
                return ResourceManager.GetString("buyer_sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sex length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_sex_range {
            get {
                return ResourceManager.GetString("buyer_sex_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 unionid is not null  的本地化字符串。
        /// </summary>
        internal static string buyer_unionid {
            get {
                return ResourceManager.GetString("buyer_unionid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 unionid length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string buyer_unionid_range {
            get {
                return ResourceManager.GetString("buyer_unionid_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 product_ids is not null  的本地化字符串。
        /// </summary>
        internal static string cart_product_ids {
            get {
                return ResourceManager.GetString("cart_product_ids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 product_ids length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string cart_product_ids_range {
            get {
                return ResourceManager.GetString("cart_product_ids_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 account is not null  的本地化字符串。
        /// </summary>
        internal static string email_account {
            get {
                return ResourceManager.GetString("email_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 account length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string email_account_range {
            get {
                return ResourceManager.GetString("email_account_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 emails is not null  的本地化字符串。
        /// </summary>
        internal static string email_emails {
            get {
                return ResourceManager.GetString("email_emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 emails length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string email_emails_range {
            get {
                return ResourceManager.GetString("email_emails_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 account is not null  的本地化字符串。
        /// </summary>
        internal static string email_notify_product_account {
            get {
                return ResourceManager.GetString("email_notify_product_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 account length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string email_notify_product_account_range {
            get {
                return ResourceManager.GetString("email_notify_product_account_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 product_i_d is not null  的本地化字符串。
        /// </summary>
        internal static string email_notify_product_product_i_d {
            get {
                return ResourceManager.GetString("email_notify_product_product_i_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 product_i_d length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string email_notify_product_product_i_d_range {
            get {
                return ResourceManager.GetString("email_notify_product_product_i_d_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 product_name is not null  的本地化字符串。
        /// </summary>
        internal static string email_notify_product_product_name {
            get {
                return ResourceManager.GetString("email_notify_product_product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 product_name length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string email_notify_product_product_name_range {
            get {
                return ResourceManager.GetString("email_notify_product_product_name_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 receive_email is not null  的本地化字符串。
        /// </summary>
        internal static string email_notify_product_receive_email {
            get {
                return ResourceManager.GetString("email_notify_product_receive_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 receive_email length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string email_notify_product_receive_email_range {
            get {
                return ResourceManager.GetString("email_notify_product_receive_email_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 scrept is not null  的本地化字符串。
        /// </summary>
        internal static string email_scrept {
            get {
                return ResourceManager.GetString("email_scrept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 scrept length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string email_scrept_range {
            get {
                return ResourceManager.GetString("email_scrept_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 account is not null  的本地化字符串。
        /// </summary>
        internal static string gift_account {
            get {
                return ResourceManager.GetString("gift_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 account length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string gift_account_range {
            get {
                return ResourceManager.GetString("gift_account_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 name is not null  的本地化字符串。
        /// </summary>
        internal static string gift_name {
            get {
                return ResourceManager.GetString("gift_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 name length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string gift_name_range {
            get {
                return ResourceManager.GetString("gift_name_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 picture is not null  的本地化字符串。
        /// </summary>
        internal static string gift_picture {
            get {
                return ResourceManager.GetString("gift_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 picture length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string gift_picture_range {
            get {
                return ResourceManager.GetString("gift_picture_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 status is not null  的本地化字符串。
        /// </summary>
        internal static string gift_status {
            get {
                return ResourceManager.GetString("gift_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 status length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string gift_status_range {
            get {
                return ResourceManager.GetString("gift_status_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 update_account is not null  的本地化字符串。
        /// </summary>
        internal static string gift_update_account {
            get {
                return ResourceManager.GetString("gift_update_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 update_account length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string gift_update_account_range {
            get {
                return ResourceManager.GetString("gift_update_account_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 account is not null  的本地化字符串。
        /// </summary>
        internal static string order_account {
            get {
                return ResourceManager.GetString("order_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 account length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_account_range {
            get {
                return ResourceManager.GetString("order_account_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 closed_comment is not null  的本地化字符串。
        /// </summary>
        internal static string order_closed_comment {
            get {
                return ResourceManager.GetString("order_closed_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 closed_comment length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_closed_comment_range {
            get {
                return ResourceManager.GetString("order_closed_comment_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 confirm_send_product_remark is not null  的本地化字符串。
        /// </summary>
        internal static string order_confirm_send_product_remark {
            get {
                return ResourceManager.GetString("order_confirm_send_product_remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 confirm_send_product_remark length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_confirm_send_product_remark_range {
            get {
                return ResourceManager.GetString("order_confirm_send_product_remark_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 gift_i_d is not null  的本地化字符串。
        /// </summary>
        internal static string order_detail_gift_i_d {
            get {
                return ResourceManager.GetString("order_detail_gift_i_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 gift_i_d length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_detail_gift_i_d_range {
            get {
                return ResourceManager.GetString("order_detail_gift_i_d_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is_comment is not null  的本地化字符串。
        /// </summary>
        internal static string order_detail_is_comment {
            get {
                return ResourceManager.GetString("order_detail_is_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is_comment length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_detail_is_comment_range {
            get {
                return ResourceManager.GetString("order_detail_is_comment_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 low_stocks is not null  的本地化字符串。
        /// </summary>
        internal static string order_detail_low_stocks {
            get {
                return ResourceManager.GetString("order_detail_low_stocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 low_stocks length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_detail_low_stocks_range {
            get {
                return ResourceManager.GetString("order_detail_low_stocks_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 product_name is not null  的本地化字符串。
        /// </summary>
        internal static string order_detail_product_name {
            get {
                return ResourceManager.GetString("order_detail_product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 product_name length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_detail_product_name_range {
            get {
                return ResourceManager.GetString("order_detail_product_name_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 spec_info is not null  的本地化字符串。
        /// </summary>
        internal static string order_detail_spec_info {
            get {
                return ResourceManager.GetString("order_detail_spec_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 spec_info length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_detail_spec_info_range {
            get {
                return ResourceManager.GetString("order_detail_spec_info_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 express_code is not null  的本地化字符串。
        /// </summary>
        internal static string order_express_code {
            get {
                return ResourceManager.GetString("order_express_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 express_code length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_express_code_range {
            get {
                return ResourceManager.GetString("order_express_code_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 express_company_name is not null  的本地化字符串。
        /// </summary>
        internal static string order_express_company_name {
            get {
                return ResourceManager.GetString("order_express_company_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 express_company_name length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_express_company_name_range {
            get {
                return ResourceManager.GetString("order_express_company_name_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 express_name is not null  的本地化字符串。
        /// </summary>
        internal static string order_express_name {
            get {
                return ResourceManager.GetString("order_express_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 express_name length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_express_name_range {
            get {
                return ResourceManager.GetString("order_express_name_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 express_no is not null  的本地化字符串。
        /// </summary>
        internal static string order_express_no {
            get {
                return ResourceManager.GetString("order_express_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 express_no length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_express_no_range {
            get {
                return ResourceManager.GetString("order_express_no_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 account is not null  的本地化字符串。
        /// </summary>
        internal static string order_log_account {
            get {
                return ResourceManager.GetString("order_log_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 account length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_log_account_range {
            get {
                return ResourceManager.GetString("order_log_account_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 account_type is not null  的本地化字符串。
        /// </summary>
        internal static string order_log_account_type {
            get {
                return ResourceManager.GetString("order_log_account_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 account_type length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_log_account_type_range {
            get {
                return ResourceManager.GetString("order_log_account_type_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 content is not null  的本地化字符串。
        /// </summary>
        internal static string order_log_content {
            get {
                return ResourceManager.GetString("order_log_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 content length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_log_content_range {
            get {
                return ResourceManager.GetString("order_log_content_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 order_id is not null  的本地化字符串。
        /// </summary>
        internal static string order_log_order_id {
            get {
                return ResourceManager.GetString("order_log_order_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 order_id length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_log_order_id_range {
            get {
                return ResourceManager.GetString("order_log_order_id_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 low_stocks is not null  的本地化字符串。
        /// </summary>
        internal static string order_low_stocks {
            get {
                return ResourceManager.GetString("order_low_stocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 low_stocks length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_low_stocks_range {
            get {
                return ResourceManager.GetString("order_low_stocks_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 other_requirement is not null  的本地化字符串。
        /// </summary>
        internal static string order_other_requirement {
            get {
                return ResourceManager.GetString("order_other_requirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 other_requirement length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_other_requirement_range {
            get {
                return ResourceManager.GetString("order_other_requirement_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 confirm_user is not null  的本地化字符串。
        /// </summary>
        internal static string order_pay_confirm_user {
            get {
                return ResourceManager.GetString("order_pay_confirm_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 confirm_user length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_pay_confirm_user_range {
            get {
                return ResourceManager.GetString("order_pay_confirm_user_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 order_id is not null  的本地化字符串。
        /// </summary>
        internal static string order_pay_order_id {
            get {
                return ResourceManager.GetString("order_pay_order_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 order_id length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_pay_order_id_range {
            get {
                return ResourceManager.GetString("order_pay_order_id_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pay_method is not null  的本地化字符串。
        /// </summary>
        internal static string order_pay_pay_method {
            get {
                return ResourceManager.GetString("order_pay_pay_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pay_method length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_pay_pay_method_range {
            get {
                return ResourceManager.GetString("order_pay_pay_method_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pay_status is not null  的本地化字符串。
        /// </summary>
        internal static string order_pay_pay_status {
            get {
                return ResourceManager.GetString("order_pay_pay_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pay_status length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_pay_pay_status_range {
            get {
                return ResourceManager.GetString("order_pay_pay_status_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 remark is not null  的本地化字符串。
        /// </summary>
        internal static string order_pay_remark {
            get {
                return ResourceManager.GetString("order_pay_remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 remark length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_pay_remark_range {
            get {
                return ResourceManager.GetString("order_pay_remark_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 trade_no is not null  的本地化字符串。
        /// </summary>
        internal static string order_pay_trade_no {
            get {
                return ResourceManager.GetString("order_pay_trade_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 trade_no length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_pay_trade_no_range {
            get {
                return ResourceManager.GetString("order_pay_trade_no_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 paystatus is not null  的本地化字符串。
        /// </summary>
        internal static string order_paystatus {
            get {
                return ResourceManager.GetString("order_paystatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 paystatus length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_paystatus_range {
            get {
                return ResourceManager.GetString("order_paystatus_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 refund_status is not null  的本地化字符串。
        /// </summary>
        internal static string order_refund_status {
            get {
                return ResourceManager.GetString("order_refund_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 refund_status length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_refund_status_range {
            get {
                return ResourceManager.GetString("order_refund_status_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 remark is not null  的本地化字符串。
        /// </summary>
        internal static string order_remark {
            get {
                return ResourceManager.GetString("order_remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 remark length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_remark_range {
            get {
                return ResourceManager.GetString("order_remark_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 area is not null  的本地化字符串。
        /// </summary>
        internal static string order_ship_area {
            get {
                return ResourceManager.GetString("order_ship_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 area_code is not null  的本地化字符串。
        /// </summary>
        internal static string order_ship_area_code {
            get {
                return ResourceManager.GetString("order_ship_area_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 area_code length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_ship_area_code_range {
            get {
                return ResourceManager.GetString("order_ship_area_code_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 area length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_ship_area_range {
            get {
                return ResourceManager.GetString("order_ship_area_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 city is not null  的本地化字符串。
        /// </summary>
        internal static string order_ship_city {
            get {
                return ResourceManager.GetString("order_ship_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 city_code is not null  的本地化字符串。
        /// </summary>
        internal static string order_ship_city_code {
            get {
                return ResourceManager.GetString("order_ship_city_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 city_code length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_ship_city_code_range {
            get {
                return ResourceManager.GetString("order_ship_city_code_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 city length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_ship_city_range {
            get {
                return ResourceManager.GetString("order_ship_city_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 order_id is not null  的本地化字符串。
        /// </summary>
        internal static string order_ship_order_id {
            get {
                return ResourceManager.GetString("order_ship_order_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 order_id length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_ship_order_id_range {
            get {
                return ResourceManager.GetString("order_ship_order_id_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 phone is not null  的本地化字符串。
        /// </summary>
        internal static string order_ship_phone {
            get {
                return ResourceManager.GetString("order_ship_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 phone length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_ship_phone_range {
            get {
                return ResourceManager.GetString("order_ship_phone_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 province is not null  的本地化字符串。
        /// </summary>
        internal static string order_ship_province {
            get {
                return ResourceManager.GetString("order_ship_province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 province_code is not null  的本地化字符串。
        /// </summary>
        internal static string order_ship_province_code {
            get {
                return ResourceManager.GetString("order_ship_province_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 province_code length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_ship_province_code_range {
            get {
                return ResourceManager.GetString("order_ship_province_code_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 province length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_ship_province_range {
            get {
                return ResourceManager.GetString("order_ship_province_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 remark is not null  的本地化字符串。
        /// </summary>
        internal static string order_ship_remark {
            get {
                return ResourceManager.GetString("order_ship_remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 remark length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_ship_remark_range {
            get {
                return ResourceManager.GetString("order_ship_remark_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sex is not null  的本地化字符串。
        /// </summary>
        internal static string order_ship_sex {
            get {
                return ResourceManager.GetString("order_ship_sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sex length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_ship_sex_range {
            get {
                return ResourceManager.GetString("order_ship_sex_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 shipaddress is not null  的本地化字符串。
        /// </summary>
        internal static string order_ship_shipaddress {
            get {
                return ResourceManager.GetString("order_ship_shipaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 shipaddress length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_ship_shipaddress_range {
            get {
                return ResourceManager.GetString("order_ship_shipaddress_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 shipname is not null  的本地化字符串。
        /// </summary>
        internal static string order_ship_shipname {
            get {
                return ResourceManager.GetString("order_ship_shipname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 shipname length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_ship_shipname_range {
            get {
                return ResourceManager.GetString("order_ship_shipname_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 tel is not null  的本地化字符串。
        /// </summary>
        internal static string order_ship_tel {
            get {
                return ResourceManager.GetString("order_ship_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 tel length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_ship_tel_range {
            get {
                return ResourceManager.GetString("order_ship_tel_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zip is not null  的本地化字符串。
        /// </summary>
        internal static string order_ship_zip {
            get {
                return ResourceManager.GetString("order_ship_zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zip length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_ship_zip_range {
            get {
                return ResourceManager.GetString("order_ship_zip_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 status is not null  的本地化字符串。
        /// </summary>
        internal static string order_status {
            get {
                return ResourceManager.GetString("order_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 status length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string order_status_range {
            get {
                return ResourceManager.GetString("order_status_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 code is not null  的本地化字符串。
        /// </summary>
        internal static string product_catagory_code {
            get {
                return ResourceManager.GetString("product_catagory_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 code length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string product_catagory_code_range {
            get {
                return ResourceManager.GetString("product_catagory_code_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 href is not null  的本地化字符串。
        /// </summary>
        internal static string product_catagory_href {
            get {
                return ResourceManager.GetString("product_catagory_href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 href length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string product_catagory_href_range {
            get {
                return ResourceManager.GetString("product_catagory_href_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 catagory_i_d is not null  的本地化字符串。
        /// </summary>
        internal static string product_catagory_i_d {
            get {
                return ResourceManager.GetString("product_catagory_i_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 catagory_i_d length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string product_catagory_i_d_range {
            get {
                return ResourceManager.GetString("product_catagory_i_d_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 name is not null  的本地化字符串。
        /// </summary>
        internal static string product_catagory_name {
            get {
                return ResourceManager.GetString("product_catagory_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 name length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string product_catagory_name_range {
            get {
                return ResourceManager.GetString("product_catagory_name_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 picture is not null  的本地化字符串。
        /// </summary>
        internal static string product_catagory_picture {
            get {
                return ResourceManager.GetString("product_catagory_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 picture length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string product_catagory_picture_range {
            get {
                return ResourceManager.GetString("product_catagory_picture_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 create_account is not null  的本地化字符串。
        /// </summary>
        internal static string product_create_account {
            get {
                return ResourceManager.GetString("product_create_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 create_account length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string product_create_account_range {
            get {
                return ResourceManager.GetString("product_create_account_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 description is not null  的本地化字符串。
        /// </summary>
        internal static string product_description {
            get {
                return ResourceManager.GetString("product_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 description length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string product_description_range {
            get {
                return ResourceManager.GetString("product_description_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 images is not null  的本地化字符串。
        /// </summary>
        internal static string product_images {
            get {
                return ResourceManager.GetString("product_images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 images length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string product_images_range {
            get {
                return ResourceManager.GetString("product_images_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 introduce is not null  的本地化字符串。
        /// </summary>
        internal static string product_introduce {
            get {
                return ResourceManager.GetString("product_introduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 introduce length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string product_introduce_range {
            get {
                return ResourceManager.GetString("product_introduce_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is_time_promotion is not null  的本地化字符串。
        /// </summary>
        internal static string product_is_time_promotion {
            get {
                return ResourceManager.GetString("product_is_time_promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is_time_promotion length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string product_is_time_promotion_range {
            get {
                return ResourceManager.GetString("product_is_time_promotion_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 isnew is not null  的本地化字符串。
        /// </summary>
        internal static string product_isnew {
            get {
                return ResourceManager.GetString("product_isnew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 isnew length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string product_isnew_range {
            get {
                return ResourceManager.GetString("product_isnew_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 keywords is not null  的本地化字符串。
        /// </summary>
        internal static string product_keywords {
            get {
                return ResourceManager.GetString("product_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 keywords length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string product_keywords_range {
            get {
                return ResourceManager.GetString("product_keywords_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 max_picture is not null  的本地化字符串。
        /// </summary>
        internal static string product_max_picture {
            get {
                return ResourceManager.GetString("product_max_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 max_picture length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string product_max_picture_range {
            get {
                return ResourceManager.GetString("product_max_picture_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msg is not null  的本地化字符串。
        /// </summary>
        internal static string product_msg_msg {
            get {
                return ResourceManager.GetString("product_msg_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msg length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string product_msg_msg_range {
            get {
                return ResourceManager.GetString("product_msg_msg_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pic is not null  的本地化字符串。
        /// </summary>
        internal static string product_msg_pic {
            get {
                return ResourceManager.GetString("product_msg_pic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pic length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string product_msg_pic_range {
            get {
                return ResourceManager.GetString("product_msg_pic_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 product_ids is not null  的本地化字符串。
        /// </summary>
        internal static string product_msg_product_ids {
            get {
                return ResourceManager.GetString("product_msg_product_ids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 product_ids length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string product_msg_product_ids_range {
            get {
                return ResourceManager.GetString("product_msg_product_ids_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 title is not null  的本地化字符串。
        /// </summary>
        internal static string product_msg_title {
            get {
                return ResourceManager.GetString("product_msg_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 title length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string product_msg_title_range {
            get {
                return ResourceManager.GetString("product_msg_title_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 name is not null  的本地化字符串。
        /// </summary>
        internal static string product_name {
            get {
                return ResourceManager.GetString("product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 name length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string product_name_range {
            get {
                return ResourceManager.GetString("product_name_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 picture is not null  的本地化字符串。
        /// </summary>
        internal static string product_picture {
            get {
                return ResourceManager.GetString("product_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 picture length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string product_picture_range {
            get {
                return ResourceManager.GetString("product_picture_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 product_h_t_m_l is not null  的本地化字符串。
        /// </summary>
        internal static string product_product_h_t_m_l {
            get {
                return ResourceManager.GetString("product_product_h_t_m_l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 product_h_t_m_l length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string product_product_h_t_m_l_range {
            get {
                return ResourceManager.GetString("product_product_h_t_m_l_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sale is not null  的本地化字符串。
        /// </summary>
        internal static string product_sale {
            get {
                return ResourceManager.GetString("product_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sale length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string product_sale_range {
            get {
                return ResourceManager.GetString("product_sale_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 search_key is not null  的本地化字符串。
        /// </summary>
        internal static string product_search_key {
            get {
                return ResourceManager.GetString("product_search_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 search_key length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string product_search_key_range {
            get {
                return ResourceManager.GetString("product_search_key_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 title is not null  的本地化字符串。
        /// </summary>
        internal static string product_title {
            get {
                return ResourceManager.GetString("product_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 title length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string product_title_range {
            get {
                return ResourceManager.GetString("product_title_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 unit is not null  的本地化字符串。
        /// </summary>
        internal static string product_unit {
            get {
                return ResourceManager.GetString("product_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 unit length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string product_unit_range {
            get {
                return ResourceManager.GetString("product_unit_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 update_account is not null  的本地化字符串。
        /// </summary>
        internal static string product_update_account {
            get {
                return ResourceManager.GetString("product_update_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 update_account length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string product_update_account_range {
            get {
                return ResourceManager.GetString("product_update_account_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 account is not null  的本地化字符串。
        /// </summary>
        internal static string seller_account {
            get {
                return ResourceManager.GetString("seller_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 account length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_account_range {
            get {
                return ResourceManager.GetString("seller_account_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 address is not null  的本地化字符串。
        /// </summary>
        internal static string seller_address {
            get {
                return ResourceManager.GetString("seller_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 address is not null  的本地化字符串。
        /// </summary>
        internal static string seller_address_address {
            get {
                return ResourceManager.GetString("seller_address_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 address length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_address_address_range {
            get {
                return ResourceManager.GetString("seller_address_address_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 city is not null  的本地化字符串。
        /// </summary>
        internal static string seller_address_city {
            get {
                return ResourceManager.GetString("seller_address_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 city length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_address_city_range {
            get {
                return ResourceManager.GetString("seller_address_city_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 contact_name is not null  的本地化字符串。
        /// </summary>
        internal static string seller_address_contact_name {
            get {
                return ResourceManager.GetString("seller_address_contact_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 contact_name length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_address_contact_name_range {
            get {
                return ResourceManager.GetString("seller_address_contact_name_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 country is not null  的本地化字符串。
        /// </summary>
        internal static string seller_address_country {
            get {
                return ResourceManager.GetString("seller_address_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 country length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_address_country_range {
            get {
                return ResourceManager.GetString("seller_address_country_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 memo is not null  的本地化字符串。
        /// </summary>
        internal static string seller_address_memo {
            get {
                return ResourceManager.GetString("seller_address_memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 memo length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_address_memo_range {
            get {
                return ResourceManager.GetString("seller_address_memo_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 phone is not null  的本地化字符串。
        /// </summary>
        internal static string seller_address_phone {
            get {
                return ResourceManager.GetString("seller_address_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 phone length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_address_phone_range {
            get {
                return ResourceManager.GetString("seller_address_phone_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 post_code is not null  的本地化字符串。
        /// </summary>
        internal static string seller_address_post_code {
            get {
                return ResourceManager.GetString("seller_address_post_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 post_code length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_address_post_code_range {
            get {
                return ResourceManager.GetString("seller_address_post_code_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 province is not null  的本地化字符串。
        /// </summary>
        internal static string seller_address_province {
            get {
                return ResourceManager.GetString("seller_address_province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 province length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_address_province_range {
            get {
                return ResourceManager.GetString("seller_address_province_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 address length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_address_range {
            get {
                return ResourceManager.GetString("seller_address_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 auth_app_id is not null  的本地化字符串。
        /// </summary>
        internal static string seller_auth_app_id {
            get {
                return ResourceManager.GetString("seller_auth_app_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 auth_app_id length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_auth_app_id_range {
            get {
                return ResourceManager.GetString("seller_auth_app_id_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 city is not null  的本地化字符串。
        /// </summary>
        internal static string seller_city {
            get {
                return ResourceManager.GetString("seller_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 city length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_city_range {
            get {
                return ResourceManager.GetString("seller_city_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 country is not null  的本地化字符串。
        /// </summary>
        internal static string seller_country {
            get {
                return ResourceManager.GetString("seller_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 country length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_country_range {
            get {
                return ResourceManager.GetString("seller_country_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 catagory_ids is not null  的本地化字符串。
        /// </summary>
        internal static string seller_coupon_catagory_ids {
            get {
                return ResourceManager.GetString("seller_coupon_catagory_ids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 catagory_ids length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_coupon_catagory_ids_range {
            get {
                return ResourceManager.GetString("seller_coupon_catagory_ids_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 product_ids is not null  的本地化字符串。
        /// </summary>
        internal static string seller_coupon_product_ids {
            get {
                return ResourceManager.GetString("seller_coupon_product_ids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 product_ids length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_coupon_product_ids_range {
            get {
                return ResourceManager.GetString("seller_coupon_product_ids_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 email is not null  的本地化字符串。
        /// </summary>
        internal static string seller_email {
            get {
                return ResourceManager.GetString("seller_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 email length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_email_range {
            get {
                return ResourceManager.GetString("seller_email_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 headimgurl is not null  的本地化字符串。
        /// </summary>
        internal static string seller_headimgurl {
            get {
                return ResourceManager.GetString("seller_headimgurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 headimgurl length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_headimgurl_range {
            get {
                return ResourceManager.GetString("seller_headimgurl_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 im_qq is not null  的本地化字符串。
        /// </summary>
        internal static string seller_im_qq {
            get {
                return ResourceManager.GetString("seller_im_qq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 im_qq length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_im_qq_range {
            get {
                return ResourceManager.GetString("seller_im_qq_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 language is not null  的本地化字符串。
        /// </summary>
        internal static string seller_language {
            get {
                return ResourceManager.GetString("seller_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 language length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_language_range {
            get {
                return ResourceManager.GetString("seller_language_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 name is not null  的本地化字符串。
        /// </summary>
        internal static string seller_name {
            get {
                return ResourceManager.GetString("seller_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 name length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_name_range {
            get {
                return ResourceManager.GetString("seller_name_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 open_id is not null  的本地化字符串。
        /// </summary>
        internal static string seller_open_id {
            get {
                return ResourceManager.GetString("seller_open_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 open_id length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_open_id_range {
            get {
                return ResourceManager.GetString("seller_open_id_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 phone is not null  的本地化字符串。
        /// </summary>
        internal static string seller_phone {
            get {
                return ResourceManager.GetString("seller_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 phone length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_phone_range {
            get {
                return ResourceManager.GetString("seller_phone_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 postcode is not null  的本地化字符串。
        /// </summary>
        internal static string seller_postcode {
            get {
                return ResourceManager.GetString("seller_postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 postcode length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_postcode_range {
            get {
                return ResourceManager.GetString("seller_postcode_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 name is not null  的本地化字符串。
        /// </summary>
        internal static string seller_prize_setting_name {
            get {
                return ResourceManager.GetString("seller_prize_setting_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 name length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_prize_setting_name_range {
            get {
                return ResourceManager.GetString("seller_prize_setting_name_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 province is not null  的本地化字符串。
        /// </summary>
        internal static string seller_province {
            get {
                return ResourceManager.GetString("seller_province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 province length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_province_range {
            get {
                return ResourceManager.GetString("seller_province_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pwd is not null  的本地化字符串。
        /// </summary>
        internal static string seller_pwd {
            get {
                return ResourceManager.GetString("seller_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pwd length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_pwd_range {
            get {
                return ResourceManager.GetString("seller_pwd_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 realname is not null  的本地化字符串。
        /// </summary>
        internal static string seller_realname {
            get {
                return ResourceManager.GetString("seller_realname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 realname length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_realname_range {
            get {
                return ResourceManager.GetString("seller_realname_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 refresh_token is not null  的本地化字符串。
        /// </summary>
        internal static string seller_refresh_token {
            get {
                return ResourceManager.GetString("seller_refresh_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 refresh_token length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_refresh_token_range {
            get {
                return ResourceManager.GetString("seller_refresh_token_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 remark is not null  的本地化字符串。
        /// </summary>
        internal static string seller_remark {
            get {
                return ResourceManager.GetString("seller_remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 remark length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_remark_range {
            get {
                return ResourceManager.GetString("seller_remark_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sex is not null  的本地化字符串。
        /// </summary>
        internal static string seller_sex {
            get {
                return ResourceManager.GetString("seller_sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sex length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_sex_range {
            get {
                return ResourceManager.GetString("seller_sex_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 unionid is not null  的本地化字符串。
        /// </summary>
        internal static string seller_unionid {
            get {
                return ResourceManager.GetString("seller_unionid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 unionid length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string seller_unionid_range {
            get {
                return ResourceManager.GetString("seller_unionid_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 app_id is not null  的本地化字符串。
        /// </summary>
        internal static string sms_app_id {
            get {
                return ResourceManager.GetString("sms_app_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 app_id length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string sms_app_id_range {
            get {
                return ResourceManager.GetString("sms_app_id_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 secrt is not null  的本地化字符串。
        /// </summary>
        internal static string sms_secrt {
            get {
                return ResourceManager.GetString("sms_secrt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 secrt length {1} to  {2} chars  的本地化字符串。
        /// </summary>
        internal static string sms_secrt_range {
            get {
                return ResourceManager.GetString("sms_secrt_range", resourceCulture);
            }
        }
    }
}
